/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.group89.app;

import javax.swing.SwingUtilities;
import com.group89.app.view.MainFrame;

public class App {
  public static void main(String[] args) {
    // disable scaling
    System.setProperty("sun.java2d.uiScale.enabled", "false");

    SwingUtilities.invokeLater(MainFrame::new);
  }
}
